services:
  - type: web
    name: librolibre
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn librolibre.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgres://YOUR_USER:YOUR_PASSWORD@YOUR_HOST:5432/YOUR_DB
      - key: DEBUG
        value: "false"
        - key: ALLOWED_HOSTS
          value: "two-librolibre-1.onrender.com"
    healthCheckPath: "/"
    routes:
      - type: redirect
        source: "/"
        destination: "/"
